# Generated by Django 4.1.2 on 2023-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrk',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
